<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>    
  </PropertyGroup>
  <ItemGroup>
    <!--<ProjectReference Include="..\Westwind.Utilities\Westwind.Utilities.csproj" />-->
  </ItemGroup>
  <ItemGroup>    
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Westwind.Utilities" Version="5.3.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>  